executor: slurm

default-resources:
  mem_mb: 10000
  runtime: 180
  cpus_per_task: 4
  slurm_partition: "standard"
  slurm_account: "kouyos.virology.uzh"
  output: "logs/{rule}/{jobid}.out"
  error: "logs/{rule}/{jobid}.err"
  #slurm_extra: "'--qos=long --mail-type=BEGIN,END,FAIL --mail-user=sara.schuetz@uzh.ch'"

jobs: 10
printshellcmds: True
rerun-incomplete: True
keep-going: True
keep-incomplete: FALSE
restart-times: 3
use-conda: True
conda-frontend: mamba

set-resources:

#########
# Fastp # 
#########
  fastp:
    cpus_per_task: 8
    mem_mb: 10000 * attempt
    runtime: 5 * attempt


##########
# FastQC # 
##########
  fastqc:
    cpus_per_task: 8
    mem_mb: 10000 * attempt
    runtime: 5 * attempt


###########
# MultiQC # 
###########
  multiqc:
    cpus_per_task: 8
    mem_mb: 10000 * attempt
    runtime: 5 * attempt


##################
## Spades # 
##################
  spades:
    cpus_per_task: 16
    mem_mb: 30000 * attempt
    runtime: 40 * attempt


##################
## Quast # 
##################
  quast:
    cpus_per_task: 8
    mem_mb: 10000 * attempt
    runtime: 30 * attempt


##################
## Prokka # 
##################
  prokka:
    cpus_per_task: 16
    mem_mb: 20000 * attempt
    runtime: 30 * attempt

##################
## Prokka reference # 
##################
  refg_prokka:
    cpus_per_task: 16
    mem_mb: 20000 * attempt
    runtime: 30 * attempt

##################
## Eggnog-mapper # 
##################
  emapper:
    cpus_per_task: 16
    mem_mb: 20000 * attempt
    runtime: 300 * attempt

##################
## Spatyper # 
##################
  spatyper:
    cpus_per_task: 8
    mem_mb: 10000 * attempt
    runtime: 30 * attempt


##################
## PIRATE # 
##################
  pirate:
    cpus_per_task: 8
    mem_mb: 10000 * attempt
    runtime: 30 * attempt


##################
## Fasttree # 
##################
  fasttree:
    cpus_per_task: 8
    mem_mb: 10000 * attempt
    runtime: 30 * attempt

##################
## IQtree # 
##################
  iqtree:
    cpus_per_task: 8
    mem_mb: 10000 * attempt
    runtime: 30 * attempt


##################
## Snippy # 
##################
  snippy:
    cpus_per_task: 16
    mem_mb: 20000 * attempt
    runtime: 120 * attempt

  snippy-core:  
    cpus_per_task: 16
    mem_mb: 20000 * attempt
    runtime: 120 * attempt

    